<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Adapting Algorithms for CAISEr • CAISEr</title>
<!-- jquery --><script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha384-nrOSfDHtoPMzJHjVTdCopGqIqeYETSXhZDFyniQ8ZHcVy08QesyHcnOUpMpqnmWq" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script><!-- Font Awesome icons --><link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.7.1/clipboard.min.js" integrity="sha384-cV+rhyOuRHc9Ub/91rihWcGmMmCXDeksTtCihMupQHSsi8GIIRDG0ThDc3HGQFJ3" crossorigin="anonymous"></script><!-- sticky kit --><script src="https://cdnjs.cloudflare.com/ajax/libs/sticky-kit/1.1.3/sticky-kit.min.js" integrity="sha256-c4Rlo1ZozqTPE2RLuvbusY3+SU1pQaJC0TjuhygMipw=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Adapting Algorithms for CAISEr">
<meta property="og:description" content="">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">CAISEr</a>
        <span class="label label-default" data-toggle="tooltip" data-placement="bottom" title="Released package">0.3.2.9001</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fa fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/Adapting_Algorithm_for_CAISEr.html">Adapting Algorithms for CAISEr</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/fcampelo/CAISEr">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Adapting Algorithms for CAISEr</h1>
                        <h4 class="author">Felipe Campelo</h4>
            
            <h4 class="date">2018-07-01</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/fcampelo/CAISEr/blob/master/vignettes/Adapting_Algorithm_for_CAISEr.Rmd"><code>vignettes/Adapting_Algorithm_for_CAISEr.Rmd</code></a></small>
      <div class="hidden name"><code>Adapting_Algorithm_for_CAISEr.Rmd</code></div>

    </div>

    
    
<div id="introduction" class="section level2">
<h2 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h2>
<p>This is a short guide to adapting existing algorithms and problem instances for running an experiment using CAISEr. In this document, we cover:</p>
<ul>
<li>Definition of instance lists</li>
<li>Adaptation of existing algorithms</li>
<li>Some stuff you can do with the results</li>
</ul>
<p>A general description of the CAISE methodology is available in our paper.<a href="#fn1" class="footnoteRef" id="fnref1"><sup>1</sup></a></p>
</div>
<div id="assembling-an-instance-list" class="section level2">
<h2 class="hasAnchor">
<a href="#assembling-an-instance-list" class="anchor"></a>Assembling an instance list</h2>
<p>As stated in the documentation of both <code>run_experiment</code> and <code>calc_nreps2</code>, each instance must be a named list containing all relevant parameters that define the problem instance. This list must contain at least the field <code>instance$FUN</code>, with the name of the problem instance function, that is, a routine that calculates <span class="math inline">\(y = f(x)\)</span>. If the instance requires additional parameters, these must also be provided as named fields. Each instance can also have an <code>alias</code>, a unique name to distinguish it from other instances. If no alias is provided, the name of the function (<code>instance$FUN</code>) is used as the instance ID.</p>
<p>The <code>Instance.list</code> parameter for <code><a href="../reference/run_experiment.html">run_experiment()</a></code> is simply a vector of these instance lists.</p>
<p>To illustrate how to adapt existing implementations to this structure, we assume that we are interested in comparing two multiobjective optimization algorithms for a (hypothetical) problem class that is well-represented by problems UF1 - UF7 (in dimensions between 10 and 40) from package <a href="https://CRAN.R-project.org/package=smoof">smoof</a>, . For this implementation to work with the <code><a href="http://www.rdocumentation.org/packages/MOEADr/topics/moead">MOEADr::moead()</a></code> routine (see next section) some manipulation is necessary, but the instance list in this case is simply a list with each element containing the name of the routine as field <code>$FUN</code> (since all function names are different, no need for aliases).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">suppressPackageStartupMessages</span>(<span class="kw">library</span>(smoof))
<span class="kw">suppressPackageStartupMessages</span>(<span class="kw">library</span>(MOEADr))

### Build function names (instances: UF1 - UF7, dimensions 10 - 40)
fname   &lt;-<span class="st"> </span><span class="kw">paste0</span>(<span class="st">"UF_"</span>, <span class="dv">1</span><span class="op">:</span><span class="dv">7</span>)
dims    &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">10</span><span class="op">:</span><span class="dv">40</span>)
allfuns &lt;-<span class="st"> </span><span class="kw">expand.grid</span>(fname, dims, <span class="dt">stringsAsFactors =</span> <span class="ot">FALSE</span>)

<span class="co"># Assemble instances list</span>
Instance.list &lt;-<span class="st"> </span><span class="kw">vector</span>(<span class="kw">nrow</span>(allfuns), <span class="dt">mode =</span> <span class="st">"list"</span>)
<span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(Instance.list)){
  Instance.list[[i]]<span class="op">$</span>FUN &lt;-<span class="st"> </span><span class="kw">paste0</span>(allfuns[i,<span class="dv">1</span>], <span class="st">"_"</span>, allfuns[i,<span class="dv">2</span>])
}

### Build the functions listed in Instance.list
<span class="co"># (so that they can be properly used)</span>
<span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(allfuns)){
  <span class="kw">assign</span>(<span class="dt">x =</span> Instance.list[[i]]<span class="op">$</span>FUN,
     <span class="dt">value =</span> MOEADr<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/MOEADr/topics/make_vectorized_smoof">make_vectorized_smoof</a></span>(<span class="dt">prob.name  =</span> <span class="st">"UF"</span>,
                    <span class="dt">dimensions =</span> allfuns[i, <span class="dv">2</span>],
                    <span class="dt">id =</span> <span class="kw">as.numeric</span>(<span class="kw">strsplit</span>(allfuns[i, <span class="dv">1</span>], <span class="st">"_"</span>)[[<span class="dv">1</span>]][<span class="dv">2</span>])))
}</code></pre></div>
</div>
<div id="adaptation-of-an-existing-algorithm-implementation" class="section level2">
<h2 class="hasAnchor">
<a href="#adaptation-of-an-existing-algorithm-implementation" class="anchor"></a>Adaptation of an existing algorithm implementation</h2>
<p>We will use the MOEA/D implementation available in the <a href="https://CRAN.R-project.org/package=MOEADr">MOEADr</a> package as our base algorithm, and assume that we are interested in comparing the performance of two versions of this algorithm: the original MOEA/D and the MOEA/D-DE (see the documentation of <a href="https://CRAN.R-project.org/package=MOEADr">MOEADr</a> and references therein for details of these methods) as solvers of the hypothetical problem class represented by the available test instances. The performance of each algorithm on each instance will be measured according to an indicator known as <em>Inverted Generational Distance</em> (IGD - details <a href="http://ieeexplore.ieee.org/document/1197687/">here</a>), for which <em>smaller = better</em>.</p>
<p>As described in the documentation of both <code><a href="../reference/run_experiment.html">run_experiment()</a></code> and <code><a href="../reference/calc_nreps2.html">calc_nreps2()</a></code>, an <code>algorithm</code> must contain an <code>algorithm$FUN</code> field (the name of the function that calls the algorithm) and any other elements/parameters that <code>algorithm$FUN</code> requires (e.g., stop criteria, operator names and parameters, etc.). An additional field, <code>algorithm$alias</code>, can be used to provide the algorithm with a unique identifier.</p>
<p>Supposing that the list in <code>algorithm</code> has fields <code>algorithm$FUN = myalgo</code>, <code>algorithm$par1 = "a"</code>, <code>algorithm$par2 = 5</code>, then the function in <code>algorithm$FUN</code> must have the following structure:</p>
<pre><code>myalgo &lt;- function(par1, par2, instance, ...){
  # do stuff
  return(results)
}</code></pre>
<p>That is, it must be able to run if called as:</p>
<pre><code># remove '$FUN' and '$alias' field from list of arguments
# and include the problem definition as field 'instance'
myargs          &lt;- algorithm[names(algorithm) != "FUN"]
myargs          &lt;- myargs[names(myargs) != "alias"]
myargs$instance &lt;- instance

# call 'algorithm$FUN' with the arguments in 'myargs'
do.call(algorithm$FUN, args = myargs)</code></pre>
<p>Finally, the <code>algorithm$FUN</code> routine must return a list object containing (at least) the performance value of the final solution obtained after a given run, in a field named <code>value</code> (e.g., <code>result$value</code>) .</p>
<p>To build the algorithm functions to be used in <code><a href="../reference/run_experiment.html">run_experiment()</a></code>, we encapsulate (almost) all algorithm parameters within a <code>myalgo()</code> function, which receives only two inputs: the instance to be solved (i.e., one element from <code>Instance.list</code>) and the specification of which version of the algorithm is to be run (the <em>original MOEA/D</em> or the <em>MOEA/D-DE</em>).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Prepare algorithm function to be used in run_experiment():</span>
myalgo &lt;-<span class="st"> </span><span class="cf">function</span>(type, instance){
  <span class="co"># Input parameters:</span>
  <span class="co">#     - type (variant to use: "original" or "moead.de")</span>
  <span class="co">#     - instance (instance to be solved, e.g., instance = Instance.list[[i]])</span>
  <span class="co"># All other parameters are set internally</span>

  ## Extract instance information to build the MOEADr problem format
  fdef  &lt;-<span class="st"> </span><span class="kw">unlist</span>(<span class="kw">strsplit</span>(instance<span class="op">$</span>FUN, <span class="dt">split =</span> <span class="st">"_"</span>))
  uffun &lt;-<span class="st"> </span>smoof<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/smoof/topics/makeUFFunction">makeUFFunction</a></span>(<span class="dt">dimensions =</span> <span class="kw">as.numeric</span>(fdef[<span class="dv">3</span>]),
                                 <span class="dt">id         =</span> <span class="kw">as.numeric</span>(fdef[<span class="dv">2</span>]))
  fattr    &lt;-<span class="st"> </span><span class="kw">attr</span>(uffun, <span class="st">"par.set"</span>)
  prob.dim &lt;-<span class="st"> </span>fattr<span class="op">$</span>pars<span class="op">$</span>x<span class="op">$</span>len
  
  ## Build MOEADr problem list
  problem &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="dt">name =</span> instance<span class="op">$</span>FUN,
                  <span class="dt">xmin =</span> fattr<span class="op">$</span>pars<span class="op">$</span>x<span class="op">$</span>lower,
                  <span class="dt">xmax =</span> fattr<span class="op">$</span>pars<span class="op">$</span>x<span class="op">$</span>upper,
                  <span class="dt">m    =</span> <span class="kw">attr</span>(uffun, <span class="st">"n.objectives"</span>))

  ## Load presets for the algorithm provided in input 'type' and 
  ## modify whatever is needed for this particular experiment
  
  algo.preset &lt;-<span class="st"> </span>MOEADr<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/MOEADr/topics/preset_moead">preset_moead</a></span>(type)
  algo.preset<span class="op">$</span>decomp<span class="op">$</span>H &lt;-<span class="st"> </span><span class="dv">99</span> <span class="co"># &lt;-- set population size</span>
  algo.preset<span class="op">$</span>stopcrit[[<span class="dv">1</span>]]<span class="op">$</span>name &lt;-<span class="st"> "maxeval"</span> <span class="co"># &lt;-- type of stop criterion</span>
  algo.preset<span class="op">$</span>stopcrit[[<span class="dv">1</span>]]<span class="op">$</span>maxeval &lt;-<span class="st"> </span><span class="dv">2000</span> <span class="op">*</span><span class="st"> </span>prob.dim <span class="co"># stop crit.</span>
  poly.ind &lt;-<span class="st"> </span><span class="kw">which</span>(<span class="kw">sapply</span>(algo.preset<span class="op">$</span>variation,
                           <span class="cf">function</span>(x){x<span class="op">$</span>name <span class="op">==</span><span class="st"> "polymut"</span>}))
  algo.preset<span class="op">$</span>variation[[poly.ind]]<span class="op">$</span>pm &lt;-<span class="st"> </span><span class="dv">1</span> <span class="op">/</span><span class="st"> </span>prob.dim <span class="co"># &lt;--- pm = 1/d</span>
  
  ## Run algorithm on "instance"
  out &lt;-<span class="st"> </span>MOEADr<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/MOEADr/topics/moead">moead</a></span>(<span class="dt">preset =</span> algo.preset, <span class="dt">problem =</span> problem,
                       <span class="dt">showpars =</span> <span class="kw">list</span>(<span class="dt">show.iters =</span> <span class="st">"none"</span>))

  ## Read reference data to calculate the IGD
  Yref  &lt;-<span class="st"> </span><span class="kw">as.matrix</span>(<span class="kw">read.table</span>(<span class="kw">paste0</span>(<span class="st">"../inst/extdata/pf_data/"</span>,
                                       fdef[<span class="dv">1</span>], fdef[<span class="dv">2</span>], <span class="st">".dat"</span>)))
  IGD =<span class="st"> </span>MOEADr<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/MOEADr/topics/calcIGD">calcIGD</a></span>(<span class="dt">Y =</span> out<span class="op">$</span>Y, <span class="dt">Yref =</span> Yref)

  ## Return IGD as field "value" in the output list
  <span class="kw">return</span>(<span class="kw">list</span>(<span class="dt">value =</span> IGD))
}</code></pre></div>
<p>Finally, the <code>Algorithm.list</code> parameter must be assembled as a list of algorithm objects (each containing fields <code>$FUN</code>, <code>$alias</code> and, in this case, <code>$type</code>).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Assemble Algorithm.list. Notice that we need to provide an alias for each </span>
<span class="co"># method, since both algorithms have the same '$FUN' argument.</span>
Algorithm.list &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="kw">list</span>(<span class="dt">FUN   =</span> <span class="st">"myalgo"</span>, 
                            <span class="dt">alias =</span> <span class="st">"Algorithm 1"</span>, 
                            <span class="dt">type  =</span> <span class="st">"original"</span>), 
                       <span class="kw">list</span>(<span class="dt">FUN   =</span> <span class="st">"myalgo"</span>, 
                            <span class="dt">alias =</span> <span class="st">"Algorithm 2"</span>, 
                            <span class="dt">type  =</span> <span class="st">"moead.de"</span>))</code></pre></div>
</div>
<div id="running-an-experiment-using-caiser" class="section level2">
<h2 class="hasAnchor">
<a href="#running-an-experiment-using-caiser" class="anchor"></a>Running an experiment using CAISEr</h2>
<p>With the definitions above it is possible now to run an experiment using the iterative sample size determination implemented in CAISEr. For that, all we have to do is define the desired experimental parameters and use <code><a href="../reference/run_experiment.html">run_experiment()</a></code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(CAISEr)
my.results &lt;-<span class="st"> </span><span class="kw"><a href="../reference/run_experiment.html">run_experiment</a></span>(<span class="dt">Instance.list  =</span> Instance.list,
                             <span class="dt">Algorithm.list =</span> Algorithm.list,
                             <span class="dt">power =</span> <span class="fl">0.8</span>,      <span class="co"># Desired power: 80%</span>
                             <span class="dt">d =</span> <span class="fl">0.5</span>,          <span class="co"># to detect differences greater</span>
                                               <span class="co"># than 0.5 standard deviations</span>
                             <span class="dt">sig.level =</span> <span class="fl">0.05</span>, <span class="co"># at a 95% confidence level. </span>
                             <span class="dt">se.max =</span> <span class="fl">0.05</span>,    <span class="co"># Measurement error: 5% </span>
                             <span class="dt">dif =</span> <span class="st">"perc"</span>,     <span class="co"># on the paired percent </span>
                                               <span class="co"># differences of means,</span>
                             <span class="dt">method =</span> <span class="st">"boot"</span>,  <span class="co"># calculated using bootstrap.</span>
                             <span class="dt">nstart =</span> <span class="dv">15</span>,      <span class="co"># Start with 20 runs/algo/inst</span>
                             <span class="dt">nmax   =</span> <span class="dv">200</span>,     <span class="co"># and do no more than 200 runs/inst</span>
                             <span class="dt">seed   =</span> <span class="dv">1234</span>)    <span class="co"># PRNG seed (for reproducibility)</span></code></pre></div>
<p>After that we can interrogate the results and perform inference, if we are so inclined. For instance, we can check if our sample of paired differences in performance is (at least approximately) Normal, so that we can assume a Normal sampling distribution of the means and use a t test with a clean conscience:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Take a look at the data summary:</span>
<span class="co"># summary(my.results)</span>
<span class="co"># print(my.results)</span>

<span class="kw">suppressPackageStartupMessages</span>(<span class="kw">library</span>(car))
car<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/car/topics/qqPlot">qqPlot</a></span>(my.results<span class="op">$</span>data.summary<span class="op">$</span>phi.j, 
            <span class="dt">pch =</span> <span class="dv">20</span>, <span class="dt">las =</span> <span class="dv">1</span>, 
            <span class="dt">ylab =</span> <span class="st">"observed results"</span>, <span class="dt">xlab =</span> <span class="st">"theoretical quantiles"</span>)</code></pre></div>
<p><img src="Adapting_Algorithm_for_CAISEr_files/figure-html/unnamed-chunk-6-1.png" width="672" style="display: block; margin: auto;"></p>
<pre><code>## [1]  3 18</code></pre>
<p>The normal QQ plot indicates that no expressive deviations of normality are present, which gives us confidence in using the t test as our inferential procedure of choice (as the sampling distribution of the means will be even more “well-behaved” than the data distribution).</p>
<p>It is also interesting to observe a few things from the summary table. First, we observed negative values of <code>phi.j</code> in the majority of instances tested, which suggests an advantage of the MOEA/D-DE over the original MOEA/D (remember, <em>smaller = better</em> for the quality indicator used). The MOEA/D-DE seems to require smaller sample sizes in most instances, suggesting a smaller variance of performance, which is also a desirable feature. Also, in three instances (UF_5_28, UF_3_29 and UF__7) the maximum number of runs/instance (<code>nmax = 200</code> in the <code><a href="../reference/run_experiment.html">run_experiment()</a></code> call) was not enough to reduce the standard error (our “measurement error” on the values of <code>phi.j</code>) below the predefined threshold of <span class="math inline">\(0.05\)</span>. There is no reason to worry in this particular case, however, since the resulting standard errors were not particularly high, and therefore their effect on the test power (resulting from the increased uncertainty in the estimation of these particular <code>phi.j</code> values) will be insignificant.</p>
<p>Since our observations <code>phi.j</code> already express paired differences per instance, we can compare the two algorithms using a simple, one-sample t.test:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(my.results<span class="op">$</span>data.summary<span class="op">$</span>phi.j)</code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  my.results$data.summary$phi.j
## t = -5.627, df = 33, p-value = 2.897e-06
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  -0.5165943 -0.2422327
## sample estimates:
##  mean of x 
## -0.3794135</code></pre>
<p>which indicates a statistically significant advantage of the MOEA/D-DE over the original MOEA/D (<span class="math inline">\(p = 2.90\times10^{-6}, df=33\)</span>), with estimated mean IGD gains of <span class="math inline">\(37.94\%\)</span> (<span class="math inline">\(CI_{0.95} = [24.22\%,51.66\%]\)</span>) over the original MOEA/D for instances belonging to the problem class of interest.</p>
<p>These results could also be used to motivate further analyses. For instance, we can observe in the summary table that the only two cases for which the MOEA/D was substantially better than the MOEA/D-DE were for different dimensions of problem UF_5, which could suggest that some specific feature of this problem jeopardizes the latter algorithm’s search mechanism. This could motivate research on which particular aspect of this problem results in this loss of performance, and on how to improve the MOEA/D-DE.</p>
<p>Finally, the full data of the experiment is contained in other fields of the output list <code>my.results</code>, and the user is encouraged to explore these. As an example, we can generate box plots and confidence intervals on the mean performance of each algorithm on each sampled instance, which could inspire new questions for the researcher.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">suppressPackageStartupMessages</span>(<span class="kw">library</span>(dplyr))
<span class="kw">suppressPackageStartupMessages</span>(<span class="kw">library</span>(ggplot2))
<span class="kw">suppressPackageStartupMessages</span>(<span class="kw">library</span>(ggridges))

<span class="co"># Adjust instance names for plotting</span>
mydata &lt;-<span class="st"> </span>my.results<span class="op">$</span>data.raw
mydata<span class="op">$</span>Instance &lt;-<span class="st"> </span><span class="kw">gsub</span>(<span class="dt">pattern =</span> <span class="st">"UF</span><span class="ch">\\</span><span class="st">_"</span>, <span class="dt">replacement =</span> <span class="st">"UF"</span>, mydata<span class="op">$</span>Instance)
mydata<span class="op">$</span>Instance &lt;-<span class="st"> </span><span class="kw">gsub</span>(<span class="dt">pattern =</span> <span class="st">"</span><span class="ch">\\</span><span class="st">_"</span>, <span class="dt">replacement =</span> <span class="st">" ("</span>, mydata<span class="op">$</span>Instance)
mydata<span class="op">$</span>Instance &lt;-<span class="st"> </span><span class="kw">sapply</span>(mydata<span class="op">$</span>Instance, <span class="dt">FUN =</span> <span class="cf">function</span>(x){<span class="kw">paste0</span>(x, <span class="st">")"</span>)})

ggplot2<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/ggplot">ggplot</a></span>(mydata, 
                <span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/aes">aes</a></span>(<span class="dt">x =</span> Observation, <span class="dt">y =</span> Instance, <span class="dt">fill =</span> Algorithm)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span>ggridges<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggridges/topics/geom_density_ridges">geom_density_ridges</a></span>(<span class="dt">alpha =</span> <span class="fl">0.7</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span>ggplot2<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/labs">ggtitle</a></span>(<span class="st">"Estimated IGD distribution"</span>, 
                   <span class="dt">subtitle =</span> <span class="st">"for each algorithm on each instance"</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span>ggplot2<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/theme">theme</a></span>(<span class="dt">legend.position =</span> <span class="st">"bottom"</span>)</code></pre></div>
<pre><code>## Picking joint bandwidth of 0.0132</code></pre>
<p><img src="Adapting_Algorithm_for_CAISEr_files/figure-html/unnamed-chunk-8-1.png" width="672"></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Calculate confidence intervals for each instance</span>
algos &lt;-<span class="st"> </span><span class="kw">unique</span>(mydata<span class="op">$</span>Algorithm)
ninstances &lt;-<span class="st"> </span><span class="kw">length</span>(my.results<span class="op">$</span>instances.sampled)
CIs &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">instance  =</span> <span class="kw">rep</span>(<span class="kw">unique</span>(mydata<span class="op">$</span>Instance, <span class="dt">times =</span> <span class="dv">2</span>)),
                  <span class="dt">algorithm =</span> <span class="kw">rep</span>(algos, <span class="dt">each =</span> ninstances),
                  <span class="dt">x.est     =</span> <span class="dv">0</span>, <span class="dt">CI.l =</span> <span class="dv">0</span>, <span class="dt">CI.u =</span> <span class="dv">0</span>)

<span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>ninstances){
  tmpdata &lt;-<span class="st"> </span>mydata <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">    </span><span class="kw"><a href="http://dplyr.tidyverse.org/reference/filter.html">filter</a></span>(Instance <span class="op">==</span><span class="st"> </span><span class="kw">unique</span>(mydata<span class="op">$</span>Instance)[i])
  myt1 &lt;-<span class="st"> </span><span class="kw">t.test</span>(tmpdata<span class="op">$</span>Observation[tmpdata<span class="op">$</span>Algorithm <span class="op">==</span><span class="st"> </span>algos[<span class="dv">1</span>]])
  myt2 &lt;-<span class="st"> </span><span class="kw">t.test</span>(tmpdata<span class="op">$</span>Observation[tmpdata<span class="op">$</span>Algorithm <span class="op">==</span><span class="st"> </span>algos[<span class="dv">2</span>]])
  
  CIs[i,<span class="dv">3</span><span class="op">:</span><span class="dv">5</span>] &lt;-<span class="st"> </span><span class="kw">c</span>(myt1<span class="op">$</span>estimate, <span class="kw">as.numeric</span>(myt1<span class="op">$</span>conf.int))
  CIs[i <span class="op">+</span><span class="st"> </span>ninstances,<span class="dv">3</span><span class="op">:</span><span class="dv">5</span>] &lt;-<span class="st"> </span><span class="kw">c</span>(myt2<span class="op">$</span>estimate, <span class="kw">as.numeric</span>(myt2<span class="op">$</span>conf.int))
}

<span class="co"># Plot individual confidence intervals for each instance</span>
myplot &lt;-<span class="st"> </span>ggplot2<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/ggplot">ggplot</a></span>(CIs, <span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/aes">aes</a></span>(<span class="dt">x =</span> instance, 
                                   <span class="dt">y =</span> x.est, <span class="dt">ymin =</span> CI.l, <span class="dt">ymax =</span> CI.u,
                                   <span class="dt">group =</span> algorithm, <span class="dt">colour =</span> algorithm,
                                   <span class="dt">fill =</span> algorithm))
myplot <span class="op">+</span><span class="st"> </span>
<span class="st">  </span>ggplot2<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/geom_linerange">geom_pointrange</a></span>(<span class="dt">position =</span> <span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/position_dodge">position_dodge</a></span>(<span class="dt">width =</span> <span class="fl">0.5</span>), <span class="dt">alpha =</span> <span class="fl">0.7</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span>ggplot2<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/labs">xlab</a></span>(<span class="st">"Instance"</span>) <span class="op">+</span><span class="st"> </span>ggplot2<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/labs">ylab</a></span>(<span class="st">"IGD"</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span>ggplot2<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/labs">ggtitle</a></span>(<span class="st">"Estimated mean IGD"</span>, 
                   <span class="dt">subtitle =</span> <span class="st">"for each algorithm on each instance"</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span>ggplot2<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/theme">theme</a></span>(<span class="dt">legend.position =</span> <span class="st">"bottom"</span>,
                 <span class="dt">axis.text.x =</span> <span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/element">element_text</a></span>(<span class="dt">angle =</span> <span class="dv">55</span>, <span class="dt">hjust =</span> <span class="dv">1</span>, <span class="dt">size =</span> <span class="dv">6</span>))</code></pre></div>
<p><img src="Adapting_Algorithm_for_CAISEr_files/figure-html/unnamed-chunk-9-1.png" width="672"></p>
</div>
<div class="footnotes">
<hr>
<ol>
<li id="fn1"><p>F. Campelo, F. Takahashi, “Sample size estimation for power and accuracy in the experimental comparison of algorithms”, under review.<a href="#fnref1">↩</a></p></li>
</ol>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#introduction">Introduction</a></li>
      <li><a href="#assembling-an-instance-list">Assembling an instance list</a></li>
      <li><a href="#adaptation-of-an-existing-algorithm-implementation">Adaptation of an existing algorithm implementation</a></li>
      <li><a href="#running-an-experiment-using-caiser">Running an experiment using CAISEr</a></li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by Felipe Campelo, Fernanda Takahashi.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="http://pkgdown.r-lib.org/">pkgdown</a>.</p>
</div>

      </footer>
</div>

  

  </body>
</html>
