#' plot.caiser.powercurve
#'
#' S3 method for plotting _caiser.powercurve_ objects (the output of
#' [calc_power_curve()]).
#'
#' @param object list object of class _caiser.powercurve_
#'                     (generated by [calc_power_curve()])
#' @param ... other parameters to be passed down to specific plotting
#'            functions (currently unused)
#'
#' @examples
#' my.cpc <- calc_power_curve(ninstances = 10)
#' plot(my.cpc)
#'
#' @export
#'

# TESTED
plot.caiser.powercurve <- function(object,...)
{

  # ========== Error catching ========== #
  assertthat::assert_that(
    "caiser.powercurve" %in% class(object),
    length(object$d) == length(object$power))
  # ==================================== #

  myvals <- summary(object)
  d <- object$d
  power <- object$power
  plot(d, power, type = "b", pch = 20, cex = 0.8, main = "Power curve")
  for (i in 1:nrow(myvals)){
    x <- myvals$d[i]
    y <- myvals$power[i]
    points(x = c(x, x), y = c(0, y), type = "l", lty = 3, lwd = 1.2)
    points(x = c(0, x), y = c(y, y), type = "l", lty = 3, lwd = 1.2)
  }

  invisible(TRUE)
}
